import NavBar from './client/components/NavBar'
import { ThemeContextProvider } from './client/context/ThemeContext'
import ThemeProvider from './client/providers/ThemeProvider'
import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'
import './globals.css'
import Footer from './client/components/Footer'
import AuthProvider from './client/providers/AuthProvider'
import { Toaster } from './client/components/ui/toaster'
import WritePostProvider from '@/app/client/providers/WritePostProvider';


const font = Nunito_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
})

export const metadata: Metadata = {
  title: 'jhonanblog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className} max-w-[100dvw] overflow-x-hidden scroll-smooth`}>
        <AuthProvider>
          <ThemeContextProvider>
            <ThemeProvider>
              <WritePostProvider>
                <div className="container-all bg-bg_main text-text_color dark:bg-bg_main_dark dark:text-text_color_dark min-h-screen">
                  <div className="container px-6 md:px-10">
                    <NavBar />
                    {children}
                    <Footer />
                  </div>
                </div>
              </WritePostProvider>
              <Toaster />
            </ThemeProvider>
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
