import type { Metadata } from 'next'
import { Titillium_Web } from 'next/font/google'
import './globals.css'



const ti = Titillium_Web({
  subsets: ['latin'],
  weight: ["300", "400", "600", "700", "200", "900"],
})

export const metadata: Metadata = {
  title: 'jhomublog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${ti.className} scroll-smooth`}>
        <div className="container px-6 md:px-10">
          <div className="min-h-[100dvh]">
            {children}
          </div>
        </div>        
      </body>
    </html>
  )
}
